//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_products
    {
        public int order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> product_amount { get; set; }
    }
}
